# Copyright (C) 2012 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/htc/shooter/setup-makefiles.sh

# Prebuilt libraries that are needed to build open-source libraries
PRODUCT_COPY_FILES += \
    vendor/htc/shooter/proprietary/system/lib/hw/camera.vendor.msm8660.so:obj/lib/hw/camera.vendor.msm8660.so \
    vendor/htc/shooter/proprietary/system/lib/libaudioalsa.so:obj/lib/libaudioalsa.so \
    vendor/htc/shooter/proprietary/system/lib/libacdbloader.so:obj/lib/libacdbloader.so \
    vendor/htc/shooter/proprietary/system/lib/libacdbmapper.so:obj/lib/libacdbmapper.so 

PRODUCT_COPY_FILES += \
    vendor/htc/shooter/proprietary/vendor/lib/libadreno_utils.so:system/vendor/lib/libadreno_utils.so \
    vendor/htc/shooter/proprietary/vendor/lib/libC2D2.so:system/vendor/lib/libC2D2.so \
    vendor/htc/shooter/proprietary/vendor/lib/libc2d2_z180.so:system/vendor/lib/libc2d2_z180.so \
    vendor/htc/shooter/proprietary/vendor/lib/libCB.so:system/vendor/lib/libCB.so \
    vendor/htc/shooter/proprietary/vendor/lib/libgsl.so:system/vendor/lib/libgsl.so \
    vendor/htc/shooter/proprietary/vendor/lib/libOpenCL.so:system/vendor/lib/libOpenCL.so \
    vendor/htc/shooter/proprietary/vendor/lib/libOpenVG.so:system/vendor/lib/libOpenVG.so \
    vendor/htc/shooter/proprietary/vendor/lib/libsc-a2xx.so:system/vendor/lib/libsc-a2xx.so \
    vendor/htc/shooter/proprietary/vendor/lib/egl/eglsubAndroid.so:system/vendor/lib/egl/eglsubAndroid.so \
    vendor/htc/shooter/proprietary/vendor/lib/egl/libEGL_adreno.so:system/vendor/lib/egl/libEGL_adreno.so \
    vendor/htc/shooter/proprietary/vendor/lib/egl/libGLESv1_CM_adreno.so:system/vendor/lib/egl/libGLESv1_CM_adreno.so \
    vendor/htc/shooter/proprietary/vendor/lib/egl/libGLESv2_adreno.so:system/vendor/lib/egl/libGLESv2_adreno.so \
    vendor/htc/shooter/proprietary/vendor/lib/egl/libGLESv2S3D_adreno.so:system/vendor/lib/egl/libGLESv2S3D_adreno.so \
    vendor/htc/shooter/proprietary/vendor/lib/egl/libq3dtools_adreno.so:system/vendor/lib/egl/libq3dtools_adreno.so \
    vendor/htc/shooter/proprietary/etc/firmware/leia_pm4_470.fw:system/etc/firmware/leia_pm4_470.fw \
    vendor/htc/shooter/proprietary/etc/firmware/leia_pfp_470.fw:system/etc/firmware/leia_pfp_470.fw \

PRODUCT_COPY_FILES += \
  vendor/htc/shooter/proprietary/system/bin/3D_calibration:/system/bin/3D_calibration \
  vendor/htc/shooter/proprietary/system/bin/3D_calibration_main:/system/bin/3D_calibration_main \
  vendor/htc/shooter/proprietary/system/bin/charging:/system/bin/charging \
  vendor/htc/shooter/proprietary/system/bin/dmagent:/system/bin/dmagent \
  vendor/htc/shooter/proprietary/system/bin/getWiMAXPropDaemond:/system/bin/getWiMAXPropDaemond \
  vendor/htc/shooter/proprietary/system/bin/load-modem.sh:/system/bin/load-modem.sh \
  vendor/htc/shooter/proprietary/system/bin/logcat2:/system/bin/logcat2 \
  vendor/htc/shooter/proprietary/system/bin/mm-qcamera-daemon:/system/bin/mm-qcamera-daemon \
  vendor/htc/shooter/proprietary/system/bin/mpdecision:/system/bin/mpdecision \
  vendor/htc/shooter/proprietary/system/bin/netmgrd:/system/bin/netmgrd \
  vendor/htc/shooter/proprietary/system/bin/qmuxd:/system/bin/qmuxd \
  vendor/htc/shooter/proprietary/system/bin/rmt_storage:/system/bin/rmt_storage \
  vendor/htc/shooter/proprietary/system/bin/sequansd:/system/bin/sequansd \
  vendor/htc/shooter/proprietary/system/bin/setWiMAXPropDaemond:/system/bin/setWiMAXPropDaemond \
  vendor/htc/shooter/proprietary/system/bin/sound8x60:/system/bin/sound8x60 \
  vendor/htc/shooter/proprietary/system/bin/thermald:/system/bin/thermald \
  vendor/htc/shooter/proprietary/system/lib/hw/sensors.shooter.so:/system/lib/hw/sensors.shooter.so \
  vendor/htc/shooter/proprietary/system/lib/hw/camera.vendor.msm8660.so:/system/lib/hw/camera.vendor.msm8660.so \
  vendor/htc/shooter/proprietary/system/lib/libacdbloader.so:/system/lib/libacdbloader.so \
  vendor/htc/shooter/proprietary/system/lib/libacdbmapper.so:/system/lib/libacdbmapper.so \
  vendor/htc/shooter/proprietary/system/lib/libaudcal.so:/system/lib/libaudcal.so \
  vendor/htc/shooter/proprietary/system/lib/libaudioalsa.so:/system/lib/libaudioalsa.so \
  vendor/htc/shooter/proprietary/system/lib/libBeautyChat.so:/system/lib/libBeautyChat.so \
  vendor/htc/shooter/proprietary/system/lib/libcameraasd.so:/system/lib/libcameraasd.so \
  vendor/htc/shooter/proprietary/system/lib/libcameraface.so:/system/lib/libcameraface.so \
  vendor/htc/shooter/proprietary/system/lib/libcamerapp.so:/system/lib/libcamerapp.so \
  vendor/htc/shooter/proprietary/system/lib/libcameraSP.so:/system/lib/libcameraSP.so \
  vendor/htc/shooter/proprietary/system/lib/libcam_oem_plugin.so:/system/lib/libcam_oem_plugin.so \
  vendor/htc/shooter/proprietary/system/lib/libchromatix_s5k3h1gx_default_video.so:/system/lib/libchromatix_s5k3h1gx_default_video.so \
  vendor/htc/shooter/proprietary/system/lib/libchromatix_s5k3h1gx_hdr.so:/system/lib/libchromatix_s5k3h1gx_hdr.so \
  vendor/htc/shooter/proprietary/system/lib/libchromatix_s5k3h1gx_hfr.so:/system/lib/libchromatix_s5k3h1gx_hfr.so \
  vendor/htc/shooter/proprietary/system/lib/libchromatix_s5k3h1gx_preview.so:/system/lib/libchromatix_s5k3h1gx_preview.so \
  vendor/htc/shooter/proprietary/system/lib/libchromatix_s5k3h1gx_zsl.so:/system/lib/libchromatix_s5k3h1gx_zsl.so \
  vendor/htc/shooter/proprietary/system/lib/libcryp98.so:/system/lib/libcryp98.so \
  vendor/htc/shooter/proprietary/system/lib/libdiag.so:/system/lib/libdiag.so \
  vendor/htc/shooter/proprietary/system/lib/libdll.so:/system/lib/libdll.so \
  vendor/htc/shooter/proprietary/system/lib/libdmtree.so:/system/lib/libdmtree.so \
  vendor/htc/shooter/proprietary/system/lib/libdsi_netctrl.so:/system/lib/libdsi_netctrl.so \
  vendor/htc/shooter/proprietary/system/lib/libdsutils.so:/system/lib/libdsutils.so \
  vendor/htc/shooter/proprietary/system/lib/libgemini.so:/system/lib/libgemini.so \
  vendor/htc/shooter/proprietary/system/lib/libgemini2.so:/system/lib/libgemini2.so \
  vendor/htc/shooter/proprietary/system/lib/libhtc_acoustic.so:/system/lib/libhtc_acoustic.so \
  vendor/htc/shooter/proprietary/system/lib/libhtccamera.so:/system/lib/libhtccamera.so \
  vendor/htc/shooter/proprietary/system/lib/libHTC_DIS.so:/system/lib/libHTC_DIS.so \
  vendor/htc/shooter/proprietary/system/lib/libhtcdm.so:/system/lib/libhtcdm.so \
  vendor/htc/shooter/proprietary/system/lib/libhtc_ril.so:/system/lib/libhtc_ril.so \
  vendor/htc/shooter/proprietary/system/lib/libhtc_ril_switch.so:/system/lib/libhtc_ril_switch.so \
  vendor/htc/shooter/proprietary/system/lib/libhtcdm.so:/system/lib/libhtcdm.so \
  vendor/htc/shooter/proprietary/system/lib/libidl.so:/system/lib/libidl.so \
  vendor/htc/shooter/proprietary/system/lib/libimage-jpeg-dec-omx-comp.so:/system/lib/libimage-jpeg-dec-omx-comp.so \
  vendor/htc/shooter/proprietary/system/lib/libimage-jpeg-enc-omx-comp.so:/system/lib/libimage-jpeg-enc-omx-comp.so \
  vendor/htc/shooter/proprietary/system/lib/libimage-omx-common.so:/system/lib/libimage-omx-common.so \
  vendor/htc/shooter/proprietary/system/lib/libllvm-arm.so:/system/lib/libllvm-arm.so \
  vendor/htc/shooter/proprietary/system/lib/libmllite.so:/system/lib/libmllite.so \
  vendor/htc/shooter/proprietary/system/lib/libmlplatform.so:/system/lib/libmlplatform.so \
  vendor/htc/shooter/proprietary/system/lib/libmm-abl.so:/system/lib/libmm-abl.so \
  vendor/htc/shooter/proprietary/system/lib/libmm-abl-oem.so:/system/lib/libmm-abl-oem.so \
  vendor/htc/shooter/proprietary/system/lib/libmmcamera_faceproc.so:/system/lib/libmmcamera_faceproc.so \
  vendor/htc/shooter/proprietary/system/lib/libmmcamera_frameproc.so:/system/lib/libmmcamera_frameproc.so \
  vendor/htc/shooter/proprietary/system/lib/libmmcamera_hdr_lib.so:/system/lib/libmmcamera_hdr_lib.so \
  vendor/htc/shooter/proprietary/system/lib/libmmcamera_image_stab.so:/system/lib/libmmcamera_image_stab.so \
  vendor/htc/shooter/proprietary/system/lib/libmmcamera_interface2.so:/system/lib/libmmcamera_interface2.so \
  vendor/htc/shooter/proprietary/system/lib/libmmcamera_rawchipproc.so:/system/lib/libmmcamera_rawchipproc.so \
  vendor/htc/shooter/proprietary/system/lib/libmmcamera_statsproc30.so:/system/lib/libmmcamera_statsproc30.so \
  vendor/htc/shooter/proprietary/system/lib/libmmcamera_statsproc31.so:/system/lib/libmmcamera_statsproc31.so \
  vendor/htc/shooter/proprietary/system/lib/libmmcamera_wavelet_lib.so:/system/lib/libmmcamera_wavelet_lib.so \
  vendor/htc/shooter/proprietary/system/lib/libmm-color-convertor.so:/system/lib/libmm-color-convertor.so \
  vendor/htc/shooter/proprietary/system/lib/libmmipl.so:/system/lib/libmmipl.so \
  vendor/htc/shooter/proprietary/system/lib/libmmjpeg.so:/system/lib/libmmjpeg.so \
  vendor/htc/shooter/proprietary/system/lib/libmmjpeg2.so:/system/lib/libmmjpeg2.so \
  vendor/htc/shooter/proprietary/system/lib/libmmjps.so:/system/lib/libmmjps.so \
  vendor/htc/shooter/proprietary/system/lib/libmmmpo.so:/system/lib/libmmmpo.so \
  vendor/htc/shooter/proprietary/system/lib/libmmmpod.so:/system/lib/libmmmpod.so \
  vendor/htc/shooter/proprietary/system/lib/libmm-omxcore.so:/system/lib/libmm-omxcore.so \
  vendor/htc/shooter/proprietary/system/lib/libmmstereo.so:/system/lib/libmmstereo.so \
  vendor/htc/shooter/proprietary/system/lib/libmmstillomx.so:/system/lib/libmmstillomx.so \
  vendor/htc/shooter/proprietary/system/lib/libmpl.so:/system/lib/libmpl.so \
  vendor/htc/shooter/proprietary/system/lib/libnetmgr.so:/system/lib/libnetmgr.so \
  vendor/htc/shooter/proprietary/system/lib/liboemcamera.so:/system/lib/liboemcamera.so \
  vendor/htc/shooter/proprietary/system/lib/libOlaEngine.so:/system/lib/libOlaEngine.so \
  vendor/htc/shooter/proprietary/system/lib/libOlaEngineNew.so:/system/lib/libOlaEngineNew.so \
  vendor/htc/shooter/proprietary/system/lib/libposteffect.so:/system/lib/libposteffect.so \
  vendor/htc/shooter/proprietary/system/lib/libqcomomxsample_jb.so:/system/lib/libqcomomxsample_jb.so \
  vendor/htc/shooter/proprietary/system/lib/libqc-opt.so:/system/lib/libqc-opt.so \
  vendor/htc/shooter/proprietary/system/lib/libqdp.so:/system/lib/libqdp.so \
  vendor/htc/shooter/proprietary/system/lib/libqmi.so:/system/lib/libqmi.so \
  vendor/htc/shooter/proprietary/system/lib/libqmiservices.so:/system/lib/libqmiservices.so \
  vendor/htc/shooter/proprietary/system/lib/libsc-a2xx.so:/system/lib/libsc-a2xx.so 
#  vendor/htc/shooter/proprietary/system/bin/htcbatt:/system/bin/htcbatt \

