# Copyright (C) 2013 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/htc/a5ul/setup-makefiles.sh

PRODUCT_COPY_FILES += \
        vendor/htc/a5ul/proprietary/blobs/gsm/bin/netmgrd:/system/blobs/gsm/bin/netmgrd \
        vendor/htc/a5ul/proprietary/blobs/gsm/bin/qmuxd:/system/blobs/gsm/bin/qmuxd \
        vendor/htc/a5ul/proprietary/blobs/chl/bin/netmgrd:/system/blobs/chl/bin/netmgrd \
        vendor/htc/a5ul/proprietary/blobs/chl/bin/qmuxd:/system/blobs/chl/bin/qmuxd \
        vendor/htc/a5ul/proprietary/blobs/gsm/vendor/lib/libdiag.so:/system/blobs/gsm/vendor/lib/libdiag.so \
        vendor/htc/a5ul/proprietary/blobs/gsm/vendor/lib/libdsi_netctrl.so:/system/blobs/gsm/vendor/lib/libdsi_netctrl.so \
        vendor/htc/a5ul/proprietary/blobs/gsm/vendor/lib/libdsnetutils.so:/system/blobs/gsm/vendor/lib/libdsnetutils.so \
        vendor/htc/a5ul/proprietary/blobs/gsm/vendor/lib/libdsutils.so:/system/blobs/gsm/vendor/lib/libdsutils.so \
        vendor/htc/a5ul/proprietary/blobs/gsm/vendor/lib/libidl.so:/system/blobs/gsm/vendor/lib/libidl.so \
        vendor/htc/a5ul/proprietary/blobs/gsm/vendor/lib/libqcci_legacy.so:/system/blobs/gsm/vendor/lib/libqcci_legacy.so \
        vendor/htc/a5ul/proprietary/blobs/gsm/vendor/lib/libqdi.so:/system/blobs/gsm/vendor/lib/libqdi.so \
        vendor/htc/a5ul/proprietary/blobs/gsm/vendor/lib/libqdp.so:/system/blobs/gsm/vendor/lib/libqdp.so \
        vendor/htc/a5ul/proprietary/blobs/gsm/vendor/lib/libqmi_cci.so:/system/blobs/gsm/vendor/lib/libqmi_cci.so \
        vendor/htc/a5ul/proprietary/blobs/gsm/vendor/lib/libqmi_client_qmux.so:/system/blobs/gsm/vendor/lib/libqmi_client_qmux.so \
        vendor/htc/a5ul/proprietary/blobs/gsm/vendor/lib/libqmi_common_so.so:/system/blobs/gsm/vendor/lib/libqmi_common_so.so \
        vendor/htc/a5ul/proprietary/blobs/gsm/vendor/lib/libqmi_csi.so:/system/blobs/gsm/vendor/lib/libqmi_csi.so \
        vendor/htc/a5ul/proprietary/blobs/gsm/vendor/lib/libqmi_encdec.so:/system/blobs/gsm/vendor/lib/libqmi_encdec.so \
        vendor/htc/a5ul/proprietary/blobs/gsm/vendor/lib/libqmiservices.so:/system/blobs/gsm/vendor/lib/libqmiservices.so \
        vendor/htc/a5ul/proprietary/blobs/gsm/vendor/lib/libqmiservices_ext.so:/system/blobs/gsm/vendor/lib/libqmiservices_ext.so \
        vendor/htc/a5ul/proprietary/blobs/gsm/vendor/lib/libqmi.so:/system/blobs/gsm/vendor/lib/libqmi.so \
        vendor/htc/a5ul/proprietary/blobs/chl/vendor/lib/libdiag.so:/system/blobs/chl/vendor/lib/libdiag.so \
        vendor/htc/a5ul/proprietary/blobs/chl/vendor/lib/libdsi_netctrl.so:/system/blobs/chl/vendor/lib/libdsi_netctrl.so \
        vendor/htc/a5ul/proprietary/blobs/chl/vendor/lib/libdsnetutils.so:/system/blobs/chl/vendor/lib/libdsnetutils.so \
        vendor/htc/a5ul/proprietary/blobs/chl/vendor/lib/libdsutils.so:/system/blobs/chl/vendor/lib/libdsutils.so \
        vendor/htc/a5ul/proprietary/blobs/chl/vendor/lib/libidl.so:/system/blobs/chl/vendor/lib/libidl.so \
        vendor/htc/a5ul/proprietary/blobs/chl/vendor/lib/libqcci_legacy.so:/system/blobs/chl/vendor/lib/libqcci_legacy.so \
        vendor/htc/a5ul/proprietary/blobs/chl/vendor/lib/libqdi.so:/system/blobs/chl/vendor/lib/libqdi.so \
        vendor/htc/a5ul/proprietary/blobs/chl/vendor/lib/libqdp.so:/system/blobs/chl/vendor/lib/libqdp.so \
        vendor/htc/a5ul/proprietary/blobs/chl/vendor/lib/libqmi_cci.so:/system/blobs/chl/vendor/lib/libqmi_cci.so \
        vendor/htc/a5ul/proprietary/blobs/chl/vendor/lib/libqmi_client_qmux.so:/system/blobs/chl/vendor/lib/libqmi_client_qmux.so \
        vendor/htc/a5ul/proprietary/blobs/chl/vendor/lib/libqmi_common_so.so:/system/blobs/chl/vendor/lib/libqmi_common_so.so \
        vendor/htc/a5ul/proprietary/blobs/chl/vendor/lib/libqmi_csi.so:/system/blobs/chl/vendor/lib/libqmi_csi.so \
        vendor/htc/a5ul/proprietary/blobs/chl/vendor/lib/libqmi_csvt_srvc.so:/system/blobs/chl/vendor/lib/libqmi_csvt_srvc.so \
        vendor/htc/a5ul/proprietary/blobs/chl/vendor/lib/libqmi_encdec.so:/system/blobs/chl/vendor/lib/libqmi_encdec.so \
        vendor/htc/a5ul/proprietary/blobs/chl/vendor/lib/libqmiservices.so:/system/blobs/chl/vendor/lib/libqmiservices.so \
        vendor/htc/a5ul/proprietary/blobs/chl/vendor/lib/libqmiservices_ext.so:/system/blobs/chl/vendor/lib/libqmiservices_ext.so \
        vendor/htc/a5ul/proprietary/blobs/gsm/vendor/lib/libnetmgr.so:/system/blobs/gsm/vendor/lib/libnetmgr.so \
        vendor/htc/a5ul/proprietary/blobs/gsm/vendor/lib/libril-qc-qmi-1.so:/system/blobs/gsm/vendor/lib/libril-qc-qmi-1.so \
        vendor/htc/a5ul/proprietary/blobs/gsm/vendor/lib/libril-qcril-hook-oem.so:/system/blobs/gsm/vendor/lib/libril-qcril-hook-oem.so \
        vendor/htc/a5ul/proprietary/blobs/chl/vendor/lib/libnetmgr.so:/system/blobs/chl/vendor/lib/libnetmgr.so \
        vendor/htc/a5ul/proprietary/blobs/chl/vendor/lib/libril-qc-qmi-1.so:/system/blobs/chl/vendor/lib/libril-qc-qmi-1.so \
        vendor/htc/a5ul/proprietary/blobs/chl/vendor/lib/libril-qcril-hook-oem.so:/system/blobs/chl/vendor/lib/libril-qcril-hook-oem.so \
